-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, 
       ROUND(C.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100.0)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
  ON C.CAR_TYPE = DP.CAR_TYPE AND DP.DURATION_TYPE = '30일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
  ON C.CAR_ID = H.CAR_ID 
 AND H.START_DATE <= '2022-11-30' 
 AND H.END_DATE >= '2022-11-01'
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
  AND H.CAR_ID IS NULL
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
