-- 코드를 작성해주세요
WITH RANKED_COLONIES AS (
    SELECT
        ID,
        SIZE_OF_COLONY,
        ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RN,
        COUNT(*) OVER () AS TOTAL_COUNT
    FROM
        ECOLI_DATA
)
SELECT
    ID,
    CASE
        WHEN RN <= ROUND(TOTAL_COUNT / 4.0) THEN 'CRITICAL'
        WHEN RN <= ROUND(TOTAL_COUNT / 2.0) THEN 'HIGH'
        WHEN RN <= ROUND(3 * TOTAL_COUNT / 4.0) THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM
    RANKED_COLONIES
ORDER BY
    ID ASC;
