-- 코드를 입력하세요
WITH MaxPrice AS (
    SELECT MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
)
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
    FROM FOOD_PRODUCT, MaxPrice
    WHERE FOOD_PRODUCT.PRICE = MaxPrice.MAX_PRICE;