-- 코드를 작성해주세요
SELECT I2.ITEM_ID, I2.ITEM_NAME, I2.RARITY
    FROM ITEM_INFO AS I
        INNER JOIN ITEM_TREE AS T
            ON I.ITEM_ID = T.PARENT_ITEM_ID
        INNER JOIN ITEM_INFO AS I2
            ON T.ITEM_ID = I2.ITEM_ID
    WHERE I.RARITY = 'RARE'
    ORDER BY I2.ITEM_ID DESC;