-- 코드를 작성해주세요
SELECT CH_ID.ITEM_ID, CH_ID.ITEM_NAME, CH_ID.RARITY
    FROM ITEM_INFO AS PA_ID
        INNER JOIN ITEM_TREE AS T
            ON PA_ID.ITEM_ID = T.PARENT_ITEM_ID
        INNER JOIN ITEM_INFO AS CH_ID
            ON T.ITEM_ID = CH_ID.ITEM_ID
    WHERE PA_ID.RARITY = 'RARE'
    ORDER BY CH_ID.ITEM_ID DESC;